export { default as addNewAppointment } from "./add-new-appointment";
export { default as getDocAppointments } from "./get-doc-appointments";
export { default as deleteDocAppointment } from "./delete-doc-appointment";
export { default as editDocAppointment } from "./edit-doc-appointment";
export { default as getClinics } from "./get-clinics";
export { default as getDoctor } from "./get-doctor";
export { default as getIllness } from "./get-illness";
export { default as getAppointmentsByDate } from "./get-appointments-by-date";
export { default as reserveAppointment } from "./reserve-appointment";
