name: Build and deploy

on:
  push:
    branches: [ develop, "fix/**" ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
  
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
            ref: 'develop'
      - name: Install dependencies
        run: cd webapp; npm ci
      - name: Build the project
        run: cd webapp; CI=false npm run build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with: 
          args: deploy --only hosting:webapp
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "webapp"
