name: Build and deploy

on:
  push:
    branches: [ develop ]

  workflow_dispatch:
  
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY : ${{ secrets.REACT_APP_API_KEY }}
      REACT_APP_AUTH_DOMAIN : ${{ secrets.REACT_APP_AUTH_DOMAIN }}
      REACT_APP_PROJECT_ID : ${{ secrets.REACT_APP_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET : ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_MESSAGE_SENDER_ID : ${{ secrets.REACT_APP_MESSAGE_SENDER_ID }}
      REACT_APP_APP_ID : ${{ secrets.REACT_APP_APP_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
            ref: ${{ github.ref }}
      - name: Install dependencies
        run: cd webapp; npm ci
      - name: Build the project
        run: cd webapp; CI=false npm run build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with: 
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "webapp"
