name: Build and deploy

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm i
      - name: Build dependencies
        run: npm run build
