name: Build and deploy

on:
  push:
    branches: [ develop, "fix/**" ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
            ref: 'develop'
      - name: Install dependencies
        run: cd webapp; npm i
      - name: Build dependencies
        run: cd webapp; false npm run build
