name: Regression

on:
  pull_request:
    branches: [ develop, DIT06 ]

  workflow_dispatch:

jobs:
  regression:
    name: Regression
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
            ref: ${{ github.ref }}
      - name: Install dependencies
        run: cd webapp; npm ci
      - name: Build the project
        run: cd webapp; CI=false npm run build
  
  runtests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3